// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjhvyicstrfiwolwcdlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaHZ5aWNzdHJmaXdvbHdjZGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTYyMjEsImV4cCI6MjA2MTI3MjIyMX0.8t8ogH2V4GvfgK0R_Xbnym8T45KbTH9HkU8Cl3N5oh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});